### ISSUE TITLE
Este complemento está quebrado - Arquivo de metadados faltando

### ISSUE THREAD

**Issue by paulohmp** [CarlosCagna/Censo_IBGE#2]
Opa, o plugin não está funcionando. Quando tento baixar algum dado o qgis fecha e posteriormente o plugin aparece como broken.

**Comment by joelschutz** [comment]
Eu consegui identificar alguns dos erros:

[ ] função *baixa_dados* precisa ser refatorada para baixar o arquivo zip corretamente
[ ] função *arruma_pastas* precisa ser avaliada para identificar se ainda é necessária
[ ] identificar bug na função *uni_setor_atributos* que está acusando erros no processamento

Mais bugs podem aparecer após estes serem solucionados. Vou mantendo atualizações aqui nesse issue.

**Comment by CarlosCagna** [comment]
Acho que foi tudo resolvido, o IBGE mudou o caminha das pastas que baixava os arquivos.
